myblog/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

myblog/blog/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    # 首页
    path('', views.index, name='home'),
    # 列表页
    path('list/', views.list, name='list'),
    # 内容页
    path('show/', views.show, name='show'),
    # 标签页
    path('tag/', views.tag, name='tag'),
    # 搜索页
    path('search/', views.search, name='search'),
    # 联系我们单页
    path('about/', views.about, name='about'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('blog/', include('blog.urls', namespace='blog'))
]

myblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from DjangoUeditor.models import UEditorField
# Create your models here.


# TODO：文章分类
class Category(models.Model):
    name = models.CharField('博客分类', max_length=100)
    index = models.ImageField(default=999, verbose_name='分类排序')

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# TODO：文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=100)

    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# TODO:推荐位
class Tui(models.Model):
    name = models.CharField('推荐位', max_length=100)

    class Meta:
        verbose_name = '推荐位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# TODO：文章
class Article(models.Model):
    title = models.CharField('标题', max_length=70)
    excerpt = models.TextField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, verbose_name='分类', blank=True, null=True)
    # 使用外键关联分类表与分类是一对多关系
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True,)
    img = models.ImageField(upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片', blank=True, null=True)
    body = UEditorField('内容', width=800, height=500,
                        toolbars="full", imagePath="upimg/", filePath="upfile/",
                        upload_settings={"imageMaxSize": 1204000},
                        settings={}, command=None, blank=True
                        )
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    '''
    文章作者，这里User是从django.contrib.auth.models导入的。
    这里我们通过 ForeigenKey 把文章和 User 关联起来
    '''
    views = models.PositiveIntegerField('阅读量', default=0)
    tui = models.ForeignKey(Tui, on_delete=models.DO_NOTHING, verbose_name='推荐位', blank=True, null=True)
    created = models.DateTimeField('发布时间', auto_now_add=True)
    modified_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'

    def __str__(self):
        return self.title


# TODO:Banner
class Banner(models.Model):
    text_info = models.CharField('标题', max_length=50, default='')
    img = models.ImageField('轮播图', upload_to='banner/')
    link_url = models.URLField('图片链接', max_length=100)
    is_active = models.BooleanField('是否是active', default=False)

    def __str__(self):
        return self.text_info

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = '轮播图'


# TODO：友情链接
class Link(models.Model):
    name = models.CharField('链接名称', max_length=20)
    linkurl = models.URLField('网址',max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'

myblog/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Article, Category, Tag, Tui, Banner, Link
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


#TODO:全局变量
def global_variable(request):
    hot = Article.objects.all().order_by('-views')[0:10]
    hottui = Article.objects.filter(tui_id=2)[0:10]
    alltag = Tag.objects.all()
    allCategory = Category.objects.all()
    return locals()


# TODO:首页
def index(request):
    banner = Banner.objects.filter(is_active=True)[0:3]
    tui = Article.objects.filter(tui=1)[0:3]
    newten = Article.objects.all().order_by('-id')[0:10]
    return render(request, 'blog/index.html', locals())

# TODO:列表页
def list(request):
    lid = request.GET['lid']
    categoryname = Category.objects.get(id=lid)
    list = Article.objects.filter(category_id=lid).order_by('created')
    # 分页
    page = request.GET.get('page')
    paginator = Paginator(list, 10)
    try:
        list = paginator.page(page)
    except PageNotAnInteger:
        list = paginator.page(1)
    except EmptyPage:
        list = paginator.page(paginator.num_pages)
    return render(request, 'blog/list.html', locals())


# TODO:内容页
def show(request):
    tid = request.GET['tid']
    cid = request.GET['cid']
    article = Article.objects.get(id=tid)
    category = Category.objects.get(id=cid)
    tag = Tag.objects.filter(article__id=tid)
    next_blog = Article.objects.filter(created__gt=article.created, category=article.category.id).first()
    provious_blog = Article.objects.filter(created__lt=article.created, category=article.category.id).last()
    article.views +=1
    article.save()
    eqtag_article = Article.objects.filter(tags__id=tid)
    return render(request, 'blog/show.html', locals())


# TODO:标签页
def tag(request):
    tid = request.GET['tid']
    tagname = Tag.objects.get(id=tid)
    list = Article.objects.filter(tags__id=tid).order_by('created')
    # 分页
    page = request.GET.get('page')
    paginator = Paginator(list, 10)
    try:
        list = paginator.page(page)
    except PageNotAnInteger:
        list = paginator.page(1)
    except EmptyPage:
        list = paginator.page(paginator.num_pages)
    return render(request, 'blog/tag.html', locals())



# TODO:搜索页
def search(request):
    ss = request.GET['name']
    # 获取搜索关键词通过标题进行匹配
    list = Article.objects.filter(title__icontains=ss)
    page = request.GET.get('page')
    paginator = Paginator(list, 10)
    try:
        list = paginator.page(page)
    except PageNotAnInteger:
        list = paginator.page(1)
    except EmptyPage:
        list = paginator.page(paginator.num_pages)
    return render(request, 'blog/search.html', locals())


# TODO:关于我们
def about(request):
    allCategory = Category.objects.all()
    return render(request, 'blog/page.html', locals())

myblog/templates/blog/base.html
<!DOCTYPE HTML>
<html>
{% load staticfiles %}
<head>
<meta charset="UTF-8">
<meta http-equiv="x-dns-prefetch-control" content="on" />
<meta http-equiv="X-UA-Compatible" content="IE=11,IE=10,IE=9,IE=8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<meta name="apple-mobile-web-app-title" content="PythonTOP,拓普Python学院">
<title>拓普Python学院,Python!</title>

    <link rel='stylesheet' id='bootstrap-css'  href='{% static "css/bootstrap.min.css" %}' type='text/css' media='all' />
    <link rel='stylesheet' id='fontawesome-css'  href='{% static "css/font-awesome.min.css" %}' type='text/css' media='all' />
    <link rel='stylesheet' id='stylesheet-css'  href='{% static "css/style.css" %}' type='text/css' media='all' />
    <link rel='stylesheet' id='raxus-css'  href='{% static "css/raxus.css" %}' type='text/css' media='all' />
    <link rel='stylesheet' id='open-social-style-css'  href='{% static "css/os.css" %}' type='text/css' media='all' />
<meta name='robots' content='index,follow' />
<meta name="keywords" content="互联网,产品经理,产品设计,用户体验,交互设计,网站运营,移动互联网">
<meta name="description" content="聚焦互联网前沿资讯，网络精华内容，交流产品心得。 每天为你速递最新、最鲜、最有料的互联网科技资讯！">
</head>

<body class="home blog site-layout-2">

<!-- 头部 -->
<header class="fix-wrap" id="fix-wrap">
<div class="fix-main clearfix pr" id="fix-main" _hover-ignore="1"> <a href="{% url 'blog:home' %}" class="index-logo">
    <img src="{% static 'picture/black-logo.png' %}" alt="拓普Python学院,Python!"></a>
<nav class="nav fl">
    <ul id="fix-list" class="fix-list clearfix">

<li id="menu-item-24086" class="menu-item"><a href="{% url 'blog:home' %}">首页</a></li>
{% for category in allCategory %}
<li id="menu-item-117720" class="menu-item">
    <a href="{% url 'blog:list' %}?lid={{ category.id }}">{{ category.name }}</a>
    </li>
{% endfor %}
<li id="menu-item-24086" class="menu-item"><a href="{% url 'blog:about' %}">关于博主</a></li>
</ul>
</nav>
    <form method="get" class="index-search  hidden-xs" action="{% url 'blog:search' %}" >
        {% csrf_token %}
        <input class="text" name='name' type="text" placeholder="输入关键字" value="">
        <button class="submit" type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>
</header>

{% block content %}
{% endblock %}

<!-- 底部 -->
<footer class="footer">
<div class="copyright"> © 2010- 2018 · All Rights Reserved
    · <a href="https://www.django.cn">Django中文网</a>
    · <a href="http://www.miibeian.gov.cn" target="_blank">湘ICP备17023990号</a> 版权所有 © Django中文网</div>
</footer>
<script src="{% static 'js/bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'js/view-history.js' %}"></script>
<script type='text/javascript' src="{% static 'js/push.js' %}" ></script>
<script type='text/javascript' src='{% static "js/jquery.min.js" %}'></script>
<script type='text/javascript' src="{% static 'js/bootstrap.min.js' %}"></script>
<script type='text/javascript' src="{% static 'js/raxus-slider.min.js' %}"></script>
<script type='text/javascript' src='{% static "js/loader.js" %}'></script>
<script type='text/javascript' src='{% static "js/bj-lazy-load.min.js" %}' ></script>
<script type='text/javascript' src='{% static "js/os.js" %}'></script>

</body>
</html>

myblog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="row">
                <!-- /banner图 -->
                <div class="col-md-6">
                    <div id="featured" class="raxus-slider" data-autoplay="3000" data-keypress="false"
                         data-thumbnail="bottom">
                        <ul class="slider-relative" id="relative">
                            {% for item in banner %}
                                <li class="slide fix-width">
                                    <a href="{{ item.link_url }}" title="{{ item.text_info }}">
                                        <img src="/media/{{ item.img }}" srcset="/media/{{ item.img }}" alt="{{ item.text_info }}"
                                             class="wp-post-image" width="370" height="290"/></a>
                                    <span class="text ani-left"><strong>{{ item.text_info }}</strong></span>
                                </li>
                            {% endfor %}
                        </ul>

                    </div>

                </div>
                <!-- /banner图 -->

                <!-- 首页推荐 -->
                <div class="col-md-6">
                    <div class="hotread ">
                        <div class="title">推荐阅读</div>
                            {% for item in tui %}
                                <div class="caption">
                                    <h4><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}" title="{{ item.title }}" rel="{{ item.tags }}">{{ item.title }}</a></h4>
                                    <p>{{ item.excerpt|truncatechars:"80" }}</p>
                                </div>
                            {% endfor %}
                    </div>
                </div>
                <!-- /今日头条 -->
            </div>
            <!-- /文章列表 -->
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title fl">最新文章</h4>
                    <div class="fr"></div>
                </div>
                <div class="row">
                    {% for item in newten %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}" title="{{ item.title }}">
                                        <img src="/media/{{ item.img }}"
                                             srcset="/media/{{ item.img }}"
                                             alt="{{ item.title }}" class="wp-post-image" width="240" height="160"/></a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}" target="_blank" title="{{ item.title }}">{{ item.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a href="/" target="_blank"
                                                                title="{{ item.title }}">{{ item.excerpt}}</a></p>
                                <div class="meta">
                                    <span class="label label-info"><a
                                        href="{% url 'blog:list' %}?lid={{ item.category.id }}">{{ item.category.name }}</a>
                                    </span>
                                <time class="item"><i class="fa fa-clock-o"></i>{{ item.created }}
                                        </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
                <!-- /文章列表 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        {% include 'blog/right.html' %}
        <div class="FriendLink hidden-xs clearfix">
            <div class="title"><h3>友情链接：</h3></div>
            <ul class="clears">

                    <li><a href="https://www.django.cn/" target="_blank">Django中文网</a></li>

                    <li><a href="https://www.django.cn/" target="_blank">django</a></li>

                    <li><a href="https://www.python.top" target="_blank">PythonTOP</a></li>

                    <li><a href="https://www.django.cn/course/" target="_blank">Django教程</a></li>

                    <li><a href="https://www.django.cn/forum/" target="_blank">Django社区</a></li>

            </ul>
        </div>
    </div>
{% endblock %}

myblog/templates/blog/list.html
{% extends "blog/base.html" %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blog:home' %}">首页</a> » <span
                    class="current">分类 » {{ categoryname }}</span></div>
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title">分类：{{ categoryname }}</h4>
                </div>
                <div class="row">
                    {% for item in list %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ categoryname.id }}" title="{{ item.title }}">
                                        <img src="/static/picture/"
                                             srcset="/media/{{ item.img }}"
                                             alt="{{ item.title }}" class="wp-post-image" width="240"
                                             height="160"/></a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ categoryname.id }}" target="_blank"
                                       title="{{ item.title }}">{{ item.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ categoryname.id }}"
                                                                target="_blank"
                                                                title="{{ item.title }}">{{ item.excerpt }}</a>
                                </p>
                                <div class="meta"><span class="label label-info"><a
                                        href="{% url 'blog:list' %}?lid={{ item.category.id }}"></a>{{ item.category }}</span>
                                    <time class="item"><i
                                            class="fa fa-clock-o"></i>{{ item.created }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="pagination">
                    <ul>
                        {% if list.has_previous %}
                            <li class="prev-page"><a href="?page={{ list.previous_page_number }}&lid={{ lid }}">上一页</a></li>
                        {% else %}
                            <li class="prev-page"></li>
                        {% endif %}
                        {% for num in list.paginator.page_range %}
                            {% if num %}
                                {% ifequal num list.number %}
                                    <li class="active"><span>{{ num }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ num }}&lid={{ lid }}">{{ num }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="disabled"><span>...</span></li>
                            {% endif %}
                        {% endfor %}
                        {% if list.has_next %}
                            <li class="next-page"><a href="?page={{ list.next_page_number }}&lid={{ lid }}">下一页</a></li>
                        {% else %}
                            <li class="prev-page"></li>
                        {% endif %}
                    </ul>

                </div>
            </div>
            <!-- /文章列表 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        {% include 'blog/right.html' %}
    </div>
{% endblock %}

myblog/templates/blog/page.html
{% extends "blog/base.html" %}
{% block content %}
     <div id="main-container" class="container clearfix">
	<section class="post-left">
		<div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blog:home' %}">首页</a> » <span class="current">关于我们</span></div>				<div class="post-main clearfix">
			<h1 class="post-title">关于我们</h1>
			<div class="post-con clearfix">
				<div class="article-meta"> <span class="item">2019-01-08</span></div>
				<article class="article-content">
					<p>1、本网站属于个人的非赢利性网站，转载的文章遵循原作者的版权声明，如果原文没有版权声明，按照目前互联网开放的原则，我们将在不通知作者的情况下，转载文章;如果原文明确注明“禁止转载”，我们一定不会转载。如果我们转载的文章不符合作者的版权声明或者作者不想让我们转载您的文章的话，请来信告知.</p>
<p>2、本网站转载文章仅为传播更多信息之目的，凡在本网站出现的信息，均仅供参考。本网站将尽力确保所提供信息的准确性及可靠性，但不保证信息的正确性和完整性，且不对因信息的不正确或遗漏导致的任何损失或损害承担责任。</p>
<p>3、任何透过本网站网页而链接及得到的资讯、产品及服务，本网站概不负责，亦不负任何法律责任。</p>
<p>4、本网站所刊发、转载的文章，其版权均归原作者所有，如其他媒体、网站或个人从本网下载使用，请在转载有关文章时务必尊重该文章的著作权，保留本网注明的“稿件来源”，并自负版权等法律责任。</p>
				</article>
			</div>
		</div>
				<!-- /文章 -->
	</section>
	<!-- /post-left -->
	<!-- /post-right -->
{% include 'blog/right.html' %}
</div>
{% endblock %}

myblog/templates/blog/search.html
{% extends "blog/base.html" %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blog:home' %}">首页</a> » <span
                    class="current">关键词 » {{ ss }}</span></div>
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title">关键词：{{ ss }}</h4>
                </div>
                <div class="row">
                    {% for item in list %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}" title="{{ item.title }}">
                                        <img src="/media/{{ item.img }}"
                                             srcset="/media/{{ item.img }}"
                                             alt="{{ item.title }}" class="wp-post-image" width="240"
                                             height="160"/></a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}" target="_blank"
                                       title="{{ item.title }}">{{ item.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}"
                                                                target="_blank"
                                                                title="{{ item.title }}">{{ item.excerpt }}</a>
                                </p>
                                <div class="meta"><span class="label label-info"><a
                                        href="{% url 'blog:list' %}?lid={{ item.category.id }}"></a>{{ item.category }}</span>
                                    <time class="item"><i
                                            class="fa fa-clock-o"></i>{{ item.created }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="pagination">
                    <ul>
                        {% if list.has_previous %}
                            <li class="prev-page"><a href="?page={{ list.previous_page_number }}&name={{ ss }}">上一页</a></li>
                        {% else %}
                            <li class="prev-page"></li>
                        {% endif %}
                        {% for num in list.paginator.page_range %}
                            {% if num %}
                                {% ifequal num list.number %}
                                    <li class="active"><span>{{ num }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ num }}&name={{ ss }}">{{ num }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="disabled"><span>...</span></li>
                            {% endif %}
                        {% endfor %}
                        {% if list.has_next %}
                            <li class="next-page"><a href="?page={{ list.next_page_number }}&name={{ ss }}">下一页</a></li>
                        {% else %}
                            <li class="prev-page"></li>
                        {% endif %}
                    </ul>

                </div>
            </div>
            <!-- /文章列表 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        {% include 'blog/right.html' %}
    </div>
{% endblock %}

myblog/templates/blog/show.html
{% extends "blog/base.html" %}
{% block content %}
        <!-- /主体 -->
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blog:home' %}">首页</a> » <a
                    href="{% url 'blog:list' %}?lid={{ category.id }}">{{ category }}</a> »
                <span class="current">正文</span></div>
            <div class="post-main clearfix">
                <h1 class="post-title">{{ article.title}}</h1>
                <div class="post-con clearfix">
                    <div class="article-meta">
                        <span class="item">分类：<a href="{% url 'blog:list' %}?lid={{ category.id }}" rel="category tag">{{ category }}</a></span>
                        <span class="item">作者：{{ article.user }}</span>
                        <span class="item">浏览：{{ article.views }}</span>
                        <span class="item">{{ article.created }}</span>

                    </div>
                    <article class="article-content">
                         {% autoescape off %}
                             <p>{{ article.body }}</p>
                         {% endautoescape %}
                    </article>

                    <div class="post-tag"><span class="fa fa-tags" aria-hidden="true"></span>标签：
                        {% for tagitem in tag %}
                            <a href="{% url 'blog:tag' %}?tid={{ tagitem.id }}" rel="tag">{{ tagitem.name }}</a>
                        {% endfor %}

                    </div>
                    <div>
                        <div><b>上一篇：</b>
                            <a href="{% url "blog:show" %}?tid={{ provious_blog.id }}&cid={{ article.category_id }}" class="article-tag">{{ provious_blog }}</a>
                        </div>
                        <div><b>下一篇：</b>

                                <a href="{% url "blog:show" %}?tid={{ next_blog.id }}&cid={{ article.category_id }}" class="article-tag">{{ next_blog }}</a>

                        </div>
                    </div>
                </div>

            </div>
            <!-- /文章 -->


            <div class="recommend  hidden-xs">
                <div class="head clearfix"><span class="sp">您可能感兴趣的:</span></div>
                <ul>
                    {% for tagitem in eqtag_article %}
                        <li>
                            <div class="pic">
                                <a href="{% url "blog:show" %}?tid={{ tagitem.id }}&cid={{ tagitem.category_id }}" title="{{ tagitem.title }}"><img
                                        src="/static/picture/quora.png"
                                        srcset="/media/{{ tagitem.img }}"
                                        alt="{{ tagitem.title }}" class="wp-post-image" width="145"
                                        height="100"/></a>
                            </div>
                            <a class="descript " href="href="{% url "blog:show" %}?tid={{ tagitem.id }}&cid={{ tagitem.category_id }}" rel="bookmark"
                               title="{{ tagitem.title }}">{{ tagitem.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        {% include 'blog/right.html' %}
    </div>
    <!-- /主体 -->
{% endblock %}

myblog/templates/blog/tag.html
{% extends "blog/base.html" %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blog:home' %}">首页</a> » <span
                    class="current">标签 » {{ tagname }}</span></div>
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title">标签：{{ tagname }}</h4>
                </div>
                <div class="row">
                    {% for item in list %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}" title="{{ item.title }}">
                                        <img src="/media/{{ item.img }}"
                                             srcset="/media/{{ item.img }}"
                                             alt="{{ item.title }}" class="wp-post-image" width="240"
                                             height="160"/></a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}" target="_blank"
                                       title="{{ item.title }}">{{ item.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a href="{% url 'blog:show' %}?tid={{ item.id }}&cid={{ item.category_id }}"
                                                                target="_blank"
                                                                title="{{ item.title }}">{{ item.excerpt }}</a>
                                </p>
                                <div class="meta"><span class="label label-info"><a
                                        href="{% url 'blog:list' %}?lid={{ item.category.id }}"></a>{{ item.category }}</span>
                                    <time class="item"><i
                                            class="fa fa-clock-o"></i>{{ item.created }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="pagination">
                    <ul>
                        {% if list.has_previous %}
                            <li class="prev-page"><a href="?page={{ list.previous_page_number }}&lid={{ lid }}">上一页</a></li>
                        {% else %}
                            <li class="prev-page"></li>
                        {% endif %}
                        {% for num in list.paginator.page_range %}
                            {% if num %}
                                {% ifequal num list.number %}
                                    <li class="active"><span>{{ num }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ num }}&lid={{ lid }}">{{ num }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="disabled"><span>...</span></li>
                            {% endif %}
                        {% endfor %}
                        {% if list.has_next %}
                            <li class="next-page"><a href="?page={{ list.next_page_number }}&lid={{ lid }}">下一页</a></li>
                        {% else %}
                            <li class="prev-page"></li>
                        {% endif %}
                    </ul>

                </div>
            </div>
            <!-- /文章列表 -->
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        {% include 'blog/right.html' %}
    </div>
{% endblock %}